# Generated by Django 3.2.5 on 2022-02-05 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det', models.CharField(max_length=50)),
                ('ammount', models.IntegerField()),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='citizen_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone_number', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip_code', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Date_of_birth', models.DateField()),
                ('identity_type', models.CharField(max_length=50)),
                ('identity_number', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
                ('report', models.ImageField(blank=True, upload_to='report_pics')),
                ('remark', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='diagnosis_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pathologist', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone_number', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip_code', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('diagnosisC', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.diagnosis_center')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insurence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('Insurence_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('taking_instructions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('need_diagnosis', models.BooleanField(default=False)),
                ('viewed_report', models.BooleanField(default=False)),
                ('meds_duration', models.CharField(max_length=50, null=True)),
                ('next_followup', models.DateField(null=True)),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('claimed_ammount', models.IntegerField(default=0)),
                ('Diagnosis_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.diagnosis')),
                ('Treating_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.doctor')),
                ('Treating_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.hospital')),
                ('bill_breakdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.bill')),
                ('meds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.prescription')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.citizen_profile')),
                ('required_tests', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.tests')),
            ],
        ),
        migrations.CreateModel(
            name='login_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='servicing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis_center',
            name='available_tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.tests'),
        ),
        migrations.AddField(
            model_name='diagnosis_center',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.diagnosis_center'),
        ),
        migrations.AddField(
            model_name='citizen_profile',
            name='insured',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizen.insurence'),
        ),
        migrations.AddField(
            model_name='citizen_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
