# Generated by Django 3.1.6 on 2022-03-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_auto_20220213_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen_profile',
            name='insured',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.insurence'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='diagnosisC',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.diagnosis_center'),
        ),
    ]
