# Generated by Django 3.1.6 on 2022-03-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0006_auto_20220315_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen_profile',
            name='sex',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
