# Generated by Django 3.1.6 on 2022-03-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0007_citizen_profile_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='meds',
        ),
        migrations.AddField(
            model_name='treatment',
            name='meds',
            field=models.ManyToManyField(blank=True, null=True, to='citizen.prescription'),
        ),
    ]
