# Generated by Django 3.1.6 on 2022-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0009_auto_20220316_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='Diagnosis_detail',
        ),
        migrations.AddField(
            model_name='treatment',
            name='Diagnosis_detail',
            field=models.ManyToManyField(blank=True, null=True, to='citizen.Diagnosis'),
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='required_tests',
        ),
        migrations.AddField(
            model_name='treatment',
            name='required_tests',
            field=models.ManyToManyField(blank=True, null=True, to='citizen.tests'),
        ),
    ]
